color0 #2A3038
color1 #E74C3C
color2 #61934F
color3 #AAAA56
color4 #2EA9FC
color5 #9B59B6
color6 #5FC8EF
color7 #B6BDAC
color8 #4A5560
color9 #FF6B6B
color10 #81C784
color11 #C5CA5A
color12 #64B5F6
color13 #CE93D8
color14 #80DEEA
color15 #DDEAFA
background #151A1E
selection_foreground #151A1E
cursor #2EA9FC
cursor_text_color #151A1E
foreground #DDEAFA
selection_background #DDEAFA
